spring.application.name=eccomerce

# Puerto del servidor
server.port=${PORT:4002}

# Configuración de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# Configuración de JPA / Hibernate
spring.jpa.database=mysql
spring.jpa.database-platform= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Subida de imagenes de productos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB

# Seguridad JWT
application.security.jwt.secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration: 86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

server.error.include-stacktrace=never

# PayPal Sandbox
paypal.client-id=${PAYPAL_CLIENT_ID:ARdxa204rOe28WvWSOJWeNF445HHz8ca7NbiUaNOlDScCHNqcnlharkzKT1Zr4seAWhNeXvzaWjir6eo}
paypal.client-secret=${PAYPAL_CLIENT_SECRET:ECHZ97J_pO6p-cZFhTLu4269aq4pYgRT3dkkzRLvLk6SbdXCw_VEn2SrobYeeq4qzUzR8nGRLloCRd5N}
paypal.base-url=https://api-m.sandbox.paypal.com
paypal.pesos-por-dolar=1450
