spring.application.name=eccomerce

# Puerto del servidor
server.port=${PORT}

# Configuración de base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.database=mysql
spring.jpa.database-platform= org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seguridad JWT
# application.security.jwt.secretKey: ${JWT_SECRET}
# application.security.jwt.expiration: 86400000
